# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b3c4cb426b141b19ddca996ef7566d9682607fd0e9340a7bd76c843b038a3c42f43beecf73c470069a5b4d7ba028c86daeee4a711fab756e4ba2b561113dd1

test:
  secret_key_base: e0cc4e9f71e67f9fe9a8562cfbe79a263579f1ac27c0a6b1b5c56c1b9221d24edc9f68ea7680d36c9aed62e553fb7a3d61a1d61d99c23b9267cf3274cad2fc82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
